apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-ngninx
  labels:
      env: prod
      app: nginx
      version: stable
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app:  nginx
        env:  production
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          imagePullPolicy: IfNotPresent

  replicas: 6
  strategy :
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
