apiVersion: v1

kind: Service

metadata:
  name: service-nodeport-nextcloud
  

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort : 30080
  selector:
    app: nextcloud-app
